import type { Locale } from '@makaan/shared/types/marketplace';

/**
 * Reviewed answers about how Makaan itself works.
 *
 * Every entry states behaviour this codebase actually implements. Nothing here
 * promises a service level, a price, or a guarantee the product does not provide,
 * because the assistant must not invent policy on a seller's or buyer's behalf.
 */
export interface KnowledgeTopic {
  id: string;
  /** Normalized keyword forms; matching is substring based on normalized text. */
  keywords: string[];
  answer: Record<Locale, string>;
}

export const KNOWLEDGE_TOPICS: ReadonlyArray<KnowledgeTopic> = [
  {
    id: 'how_to_list',
    keywords: [
      'ازاي اعلن',
      'ازاي انزل',
      'ازاي اضيف',
      'انزل اعلان',
      'اضيف عقار',
      'اعلن عن شقتي',
      'اعرض عقار',
      'عايز اعلن',
      'عايز ابيع',
      'عايز اجر',
      'how do i list',
      'how to list',
      'post a listing',
      'add a property',
      'sell my',
      'list my',
    ],
    answer: {
      ar: 'عشان تعرض عقارك: ادخل من زرار «اعرض عقارك» في الأعلى، سجّل برقم تليفونك وكود التأكيد، وحدّد إنت مالك ولا وسيط معلن. بعدها تملا بيانات العقار على خمس خطوات، تحدّد المكان بالظبط على الخريطة، وترفع من ٣ لـ ١٠ صور. لما تبعت الإعلان بيروح لمراجعة بشرية، ومش بيظهر للناس غير بعد الموافقة.',
      en: 'To list a property: open “List your property” in the header, sign in with your phone number and the confirmation code, then declare whether you are an owner or a declared agent. You then fill the property details across five steps, place the exact location on the map, and upload between 3 and 10 photos. Once submitted it goes to a human moderator, and it only becomes public after approval.',
    },
  },
  {
    id: 'approximate_location',
    keywords: [
      'ليه المكان تقريبي',
      'مكان تقريبي',
      'الموقع التقريبي',
      'العنوان بالظبط',
      'العنوان الدقيق',
      'مكان بالظبط',
      'ليه مش باين',
      'خصوصيه المكان',
      'why approximate',
      'exact location',
      'exact address',
      'precise location',
      'why is the location',
    ],
    answer: {
      ar: 'إحنا بنحفظ المكان الدقيق للمراجعة بس، وعمره ما بيظهر للناس. المشرف هو اللي بيقرر يعرض إيه: يا إما المنطقة بس من غير دبوس على الخريطة، يا إما نقطة تقريبية بيحطها بنفسه على بُعد من ١٠٠ لـ ٥٠٠ متر من المكان الحقيقي. ده بيحمي خصوصية صاحب العقار وبيخليك في نفس الوقت تعرف المنطقة قبل ما تتواصل.',
      en: 'The exact location is stored for moderation only and is never exposed publicly. A moderator decides what is shown: either the area alone with no map pin, or an approximate point they place themselves between 100 and 500 metres from the real location. This protects the seller’s privacy while still telling you which area the home is in before you reach out.',
    },
  },
  {
    id: 'owner_vs_agent',
    keywords: [
      'الفرق بين مالك ووسيط',
      'الفرق بين المالك والوسيط',
      'يعني ايه وسيط معلن',
      'يعني ايه مالك متحقق',
      'مالك متحقق منه',
      'وسيط معلن',
      'owner vs agent',
      'difference between owner',
      'what is a declared agent',
      'verified owner mean',
      'what does verified',
    ],
    answer: {
      ar: 'فيه تلات علامات على كل إعلان. «مالك متحقق منه» يعني المشرف راجع إنه صاحب العقار فعلاً. «مالك لسه مش متحقق منه» يعني معلن نفسه كمالك بس لسه ما اتحققش. «وسيط معلن» يعني الإعلان من سمسار، وده مسموح بس بشرط يبان بوضوح وبيتراجع بشكل أدق. وتقدر تفلتر وتشوف إعلانات الملاك بس من فلتر «المُعلن».',
      en: 'Every listing carries one of three labels. “Verified owner” means a moderator confirmed they own the property. “Owner not verified” means they declared themselves an owner but have not been verified yet. “Declared agent” means the listing comes from a broker — allowed, but it must be clearly labelled and is moderated more strictly. You can use the participation filter to see owner listings only.',
    },
  },
  {
    id: 'contact_seller',
    keywords: [
      'ازاي اتواصل',
      'ازاي اكلم',
      'رقم التليفون',
      'رقم صاحب',
      'رقم المالك',
      'الرقم فين',
      'واتساب',
      'اتصل',
      'how do i contact',
      'contact the seller',
      'phone number',
      'whatsapp',
      'call the owner',
    ],
    answer: {
      ar: 'افتح صفحة الإعلان واستخدم زرار الاتصال أو الواتساب اللي جواها. الرقم نفسه مش بيتعرض في الصفحة ولا في نتائج البحث — الزرار بيفتحلك اتصال مباشر من خلال رابط صالح لاستخدام واحد وبينتهي بعد خمس دقايق. ده بيحمي أصحاب العقارات من جمع أرقامهم أو استخدامها في سبام.',
      en: 'Open the listing page and use the call or WhatsApp button there. The number itself is never shown on the page or in search results — the button opens the contact through a single-use link that expires after five minutes. This protects sellers from having their numbers harvested or spammed.',
    },
  },
  {
    id: 'review_and_publishing',
    keywords: [
      'المراجعه',
      'مراجعه',
      'الاعلان بيتراجع',
      'ليه اعلاني',
      'امتي هيظهر',
      'اتقبل',
      'اترفض',
      'الاعلان بيقعد قد ايه',
      'الاعلان بيفضل ظاهر',
      'مده الاعلان',
      'صلاحيه الاعلان',
      'الاعلان بينتهي',
      'moderation',
      'review process',
      'when will my listing',
      'why was my listing',
      'how long does a listing',
      'listing expire',
      'approved',
      'rejected',
    ],
    answer: {
      ar: 'كل إعلان بيتراجع من مشرف بشري قبل ما يظهر. المشرف بيتأكد إن البيانات كاملة، الصور سليمة، والمكان مظبوط، وبيحدد شكل الموقع اللي هيظهر للناس. لو الإعلان اترفض هتوصلك النتيجة والسبب، وتقدر تعدّل وتبعته تاني. الإعلان اللي بيتوافق عليه بيفضل ظاهر ٣٠ يوم من تاريخ الموافقة.',
      en: 'Every listing is reviewed by a human moderator before it appears. The moderator checks that the details are complete, the photos are sound, and the location is accurate, and decides how the public location is shown. If a listing is rejected you receive the outcome and the reason, and you can edit and resubmit it. An approved listing stays visible for 30 days from the approval date.',
    },
  },
  {
    id: 'saving_listings',
    keywords: [
      'احفظ',
      'المفضله',
      'العقارات المحفوظه',
      'اشتراك',
      'محتاج حساب',
      'لازم اسجل',
      'save a listing',
      'saved homes',
      'favourites',
      'favorites',
      'need an account',
      'sign up',
    ],
    answer: {
      ar: 'مش محتاج تعمل حساب عشان تدوّر أو تحفظ عقارات. اضغط على علامة الحفظ في أي إعلان وهتلاقيه في صفحة «عقاراتك المحفوظة». الحساب مطلوب بس لو إنت اللي هتعرض عقار، وساعتها بيتعمل برقم تليفون وكود تأكيد.',
      en: 'You do not need an account to browse or save homes. Use the save control on any listing and it appears on your “Saved homes” page. An account is only needed if you want to list a property, and that is created with a phone number and a confirmation code.',
    },
  },
  {
    id: 'coverage',
    keywords: [
      'بتغطوا',
      'انهي مناطق',
      'المناطق المتاحه',
      'مناطق',
      'محافظات',
      'اسكندريه',
      'الساحل',
      'مكاتب',
      'محل',
      'اداري',
      'تجاري',
      'which areas',
      'what areas',
      'do you cover',
      'coverage',
      'alexandria',
      'commercial',
      'office space',
      'shop',
    ],
    answer: {
      ar: 'الإصدار الأول من مكان للعقارات السكنية في القاهرة بس، وللبيع أو الإيجار طويل الأجل. لسه مفيش عقارات تجارية أو إدارية ولا إيجار مصايف أو يومي، ولا مدن تانية. أنواع العقارات المتاحة: شقة، فيلا، دوبلكس، بنتهاوس، ستوديو، تاون هاوس، وشاليه.',
      en: 'The first release of Makaan covers residential property in Cairo only, for sale or long-term rent. Commercial and office space, holiday or short-term rentals, and other cities are not covered yet. The available property types are apartment, villa, duplex, penthouse, studio, townhouse, and chalet.',
    },
  },
  {
    id: 'trust_and_safety',
    keywords: [
      'نصب',
      'نصاب',
      'اعلانات وهميه',
      'مضمون',
      'امان',
      'موثوق',
      'اثق',
      'مكرر',
      'scam',
      'fake listing',
      'is it safe',
      'trust',
      'duplicate',
    ],
    answer: {
      ar: 'كل إعلان لازم يعدي على مراجعة بشرية قبل ما ينشر، والمُعلن بيتقال عليه مالك ولا وسيط بوضوح، والمكان الدقيق وأرقام التليفونات محميين. لو شفت إعلان مريب، الأحسن إنك تبلّغ عنه بدل ما تكمل معاه. خلي بالك: إحنا بنراجع البيانات المعروضة، بس ده مش بديل عن إنك تعاين العقار وتتأكد من الأوراق بنفسك قبل أي دفع.',
      en: 'Every listing passes human review before publishing, each seller is clearly labelled as an owner or an agent, and exact locations and phone numbers are protected. If a listing looks suspicious, report it rather than continuing with it. Keep in mind that reviewing the submitted details is not a substitute for visiting the property and checking the paperwork yourself before paying anything.',
    },
  },
  {
    id: 'costs',
    keywords: [
      'بفلوس',
      'بكام',
      'عموله',
      'مجاني',
      'رسوم',
      'اشتراك شهري',
      'ادفع',
      'ترويج',
      'اعلان مميز',
      'commission',
      'fees',
      'free to use',
      'do i pay',
      'promoted',
      'featured listing',
    ],
    answer: {
      ar: 'مفيش ترويج مدفوع في مكان — إعلانات الملاك بتاخد نفس الظهور من غير ما تدفع حاجة عشان تبان، والوسطاء مش بياخدوا أفضلية مخفية في الترتيب. لو عندك سؤال عن أي رسوم تانية، ده قرار بيرجع لأصحاب المنتج مش حاجة أقدر أأكدها من هنا.',
      en: 'Makaan has no paid promotion — owner listings get the standard visibility without paying for it, and agents receive no hidden ranking advantage. For any question about other charges, that is a decision for the product owners rather than something I can confirm here.',
    },
  },
  {
    id: 'language',
    keywords: [
      'انجليزي',
      'عربي',
      'اللغه',
      'غير اللغه',
      'english',
      'arabic',
      'change language',
      'switch language',
    ],
    answer: {
      ar: 'الموقع شغال بالعربي والإنجليزي بالكامل. تقدر تبدّل اللغة من زرار اللغة في أعلى الصفحة، وأنا هرد عليك بنفس اللغة اللي مختارها.',
      en: 'The site is fully available in Arabic and English. You can switch from the language control in the header, and I will reply in whichever language you have selected.',
    },
  },
];

/** Questions that ask for data the public interface deliberately never returns. */
export const PRIVACY_BOUNDARY_KEYWORDS: ReadonlyArray<string> = [
  'العنوان بالظبط',
  'العنوان الدقيق',
  'العنوان كامل',
  'الشارع',
  'رقم العماره',
  'احداثيات',
  'الاحداثيات',
  'المكان الحقيقي',
  'ادي رقم',
  'اديني رقم',
  'رقم البايع',
  'رقم المعلن',
  'ايميل المالك',
  'بيانات المالك',
  'exact address',
  'full address',
  'street name',
  'building number',
  'coordinates',
  'gps',
  'give me the number',
  'seller phone',
  'owner email',
];

export const GREETING_KEYWORDS: ReadonlyArray<string> = [
  'السلام عليكم',
  'اهلا',
  'ازيك',
  'صباح الخير',
  'مساء الخير',
  'هاي',
  'مرحبا',
  'hello',
  'hi',
  'hey',
  'good morning',
  'good evening',
];

export const HELP_KEYWORDS: ReadonlyArray<string> = [
  'تقدر تعمل ايه',
  'بتعمل ايه',
  'ساعدني',
  'مساعده',
  'ايه ده',
  'انت مين',
  'what can you do',
  'help me',
  'who are you',
  'what is this',
];

/**
 * Well-known Egyptian places that are commonly asked about. They are only treated
 * as out of scope when no active governed area matched first, so adding a real
 * area later automatically stops this list from applying to it.
 */
export const UNSUPPORTED_AREA_HINTS: ReadonlyArray<string> = [
  'مدينه نصر',
  'الشيخ زايد',
  'زايد',
  '6 اكتوبر',
  'اكتوبر',
  'المهندسين',
  'الزمالك',
  'الدقي',
  'المعصره',
  'حلوان',
  'شبرا',
  'العبور',
  'الشروق',
  'الرحاب',
  'مدينتي',
  'بدر',
  'العاصمه الاداريه',
  'الاسكندريه',
  'اسكندريه',
  'الساحل الشمالي',
  'العين السخنه',
  'الغردقه',
  'شرم الشيخ',
  'المنصوره',
  'طنطا',
  'الجيزه',
  'الهرم',
  'فيصل',
  'nasr city',
  'sheikh zayed',
  'october',
  'mohandessin',
  'zamalek',
  'dokki',
  'helwan',
  'shorouk',
  'rehab',
  'madinaty',
  'new capital',
  'alexandria',
  'north coast',
  'sokhna',
  'hurghada',
  'sharm',
  'giza',
  'haram',
];
